## -*- docker-image-name: "mcreations/fusiondirectory" -*-

FROM rezarahimi/debian-fusiondirectory
MAINTAINER Reza Rahimi <rahimi@m-creations.net>

ENV LDAP_PORT 389
ENV LDAP_HOST ldap-server
ENV LDAP_SERVER_URL ldap://${LDAP_HOST}:${LDAP_PORT}
ENV FUSIONDIRECTORY_VERSION 1.0.8.2
ENV FUSIONDIRECTORY_DEB_PKG_VERSION 1.0.8.2-5+deb8u1
ENV LDAP_ROOT Manager
ENV LDAP_TLS TRUE
ENV TLS_REQCERT never

# Variables FusionDirectory plugins (FALSE = Not installed)
ENV PLUGIN_ADDRESSBOOK FALSE
ENV PLUGIN_ALIAS FALSE
ENV PLUGIN_APACHE2 FALSE
ENV PLUGIN_APPLICATIONS FALSE
ENV PLUGIN_ARGONAUT FALSE
ENV PLUGIN_ASTERISK FALSE
ENV PLUGIN_AUTOFS FALSE
ENV PLUGIN_CERTIFICATES FALSE
ENV PLUGIN_CYRUS FALSE
ENV PLUGIN_DATABASE-CONNECTOR FALSE
ENV PLUGIN_DEBCONF FALSE
ENV PLUGIN_DEVELOPERS FALSE
ENV PLUGIN_DHCP FALSE
ENV PLUGIN_DNS FALSE
ENV PLUGIN_DOVECOT FALSE
ENV PLUGIN_DSA FALSE
ENV PLUGIN_EJBCA FALSE
ENV PLUGIN_FAI FALSE
ENV PLUGIN_FAX FALSE
ENV PLUGIN_FREERADIUS FALSE
ENV PLUGIN_FUSIONINVENTORY FALSE
ENV PLUGIN_GAME FALSE
ENV PLUGIN_GPG FALSE
ENV PLUGIN_IPMI FALSE
ENV PLUGIN_KOLAB FALSE
ENV PLUGIN_LDAPDUMP FALSE
ENV PLUGIN_LDAPMANAGER FALSE
ENV PLUGIN_MAIL FALSE
ENV PLUGIN_NAGIOS FALSE
ENV PLUGIN_NETGROUPS FALSE
ENV PLUGIN_OPENSTACK-COMPUTE FALSE
ENV PLUGIN_OPSI FALSE
ENV PLUGIN_PERSONAL FALSE
ENV PLUGIN_PPOLICY FALSE
ENV PLUGIN_PUPPET FALSE
ENV PLUGIN_PUREFTPD FALSE
ENV PLUGIN_QUOTA FALSE
ENV PLUGIN_REPOSITORY FALSE
ENV PLUGIN_RSYSLOG FALSE
ENV PLUGIN_SAMBA FALSE
ENV PLUGIN_SOGO FALSE
ENV PLUGIN_SQUID FALSE
ENV PLUGIN_SSH FALSE
ENV PLUGIN_SUDO FALSE
ENV PLUGIN_SUPANN FALSE
ENV PLUGIN_SYMPA FALSE
ENV PLUGIN_SYSTEMS FALSE
ENV PLUGIN_UW-IMAP FALSE
ENV PLUGIN_WEBLINK FALSE
ENV PLUGIN_WEBSERVICE FALSE


ADD image/root/ /


RUN chown -R root:root /usr/share/fusiondirectory/include/jsonrpcphp/ && \
    a2dissite 000-default && \
    a2disconf fusiondirectory && \
    a2ensite fusiondirectory && \
    a2enmod ssl

# Configure ldap
RUN echo  "TLS_REQCERT    $TLS_REQCERT" >> /etc/ldap/ldap.conf

# Install FusionDirectory plugins


EXPOSE 80

CMD ["/start-fd"]
